Update update_sonyliv_json.yml

diff --git a/.github/workflows/update_sonyliv_json.yml b/.github/workflows/update_sonyliv_json.yml
--- a/.github/workflows/update_sonyliv_json.yml
+++ b/.github/workflows/update_sonyliv_json.yml
@@ -30,11 +30,14 @@ jobs:
           curl -sS -f -o sonyliv2.json "https://raw.githubusercontent.com/doctor-8trange/zyphora/refs/heads/main/data/sony.json" || echo "⚠️ sonyliv2.json fetch failed"
           curl -sS -f -L -o sonyliv2.m3u "https://raw.githubusercontent.com/doctor-8trange/zyphora/refs/heads/main/data/sony.m3u" || echo "⚠️ sonyliv2.m3u fetch failed"
 
+          # ⬇️ NEW: Fetch sony.m3u
+          curl -sS -f -L -o sony.m3u "https://premiumplugx.com/Sliv/sony_playlist.php?m3u" || echo "⚠️ sony.m3u fetch failed"
+
           echo "🚀 SonyLiv Synced | IST: $(date +'%Y-%m-%d %H:%M:%S') | ID: $RANDOM" >> sonyliv.txt
       - name: Commit and Push
         run: |
           export TZ="Asia/Kolkata"
-          git add sonyliv.json sonyliv.m3u sonyliv2.json sonyliv2.m3u sonyliv.txt
+          git add sonyliv.json sonyliv.m3u sonyliv2.json sonyliv2.m3u sony.m3u sonyliv.txt
           git diff --cached --quiet && echo "No changes to commit" && exit 0
           git commit -m "SonyLiv Database Updated ✅ [$(date +'%d-%m-%Y %H:%M')]"
           git push origin main
